### PR TITLE
Fix max-len errors

### PR DESCRIPTION
**Pull request by BigBlueHat**
Follow-up to d2a7db7816cd7af6c9cfadd4339bafa93e10fb71

### CODE REVIEW

**Comment by iherman** [comment]
I am fine with these...

**Comment by BigBlueHat** [comment]
@iherman cool. 😃 You'll have to merge them though. 😁

**Comment by iherman** [comment]
@BigBlueHat tough luck, but I have added you as a collaborator to the repo with a write permission:-)

**Comment by iherman** [comment]
Ie, you can merge yourself (now and in the future)

**Comment by BigBlueHat** [comment]
@iherman gah!! 😜 

I'll still send PRs for "big stuff" so we can review them.

Huge thanks for the super powers!

**Pull request merged**
