### PR TITLE
Markdown preview

### PR DESCRIPTION
**Pull request by BigBlueHat**
Does what it says on the tin. 😸

### CODE REVIEW

**Comment by iherman** [comment]
Dam'n! When I was doing the schema validation, I thought this would be a nice extra feature, worth adding it.  You preempted me...

I was just wondering (but that may be too hard or simply not possible): is it possible to sync the position of the source and the preview? Ie, if I make a change on the markdown source (because that is editable) then the preview would automatically scroll roughly to the right place... I know the markdown preview of my editor does something like that. But if it is too hard, then we can let it go.

**Comment by iherman** [comment]
Oh, if it was not clear: I am of course in favour of merging!

One minor styling things: I tried to avoid putting code _into_ the `window.addEventListener('load',()=>...` part. There are lots of entries there and I found it more readable if the functions are factored out, so to say. Do you think you can do that with the markdown related call backs, just to have a unified code style?

**Comment by BigBlueHat** [comment]
@iherman k. Those functions are refactored.

We're also going to need to do something about these conflicting build outputs... They're unavoidable...and easily resolvable by simply re-building and committing the latest. Likely there's some robot somewhere that'll do that for us...

**Comment by iherman** [comment]
I am not sure what we can do with those conflicting things, to be honest. I am sure there are ways to automatically do somethings in github, but I am not really familiar with these things...

I would merge the whole thing and after all the merge, redo the compilation locally and commit it. We can the be sure that the compiled thing does reflect the latest status.

Go ahead and merge!

**Comment by BigBlueHat** [comment]
Dropped the "built bits" commit--which I'll rerun and add back on master.

**Pull request merged**
