### PR TITLE
Action lists

### PR DESCRIPTION
**Pull request by iherman**
Adding the possibility of recording actions in a separate (JSON) file.

At this moment, this is still beta; in particular, it does not work with the browserview yet at all. However, it is necessary to make a merge to be able to test it properly with a real setup; the goal is to have it tested with the JSON-LD WG. Once a complete round is operational, further refinement will come.

@BigBlueHat do you have any reasons why you would prefer _not_ to merge this?

The way it would work:

- If the config (or the command line) provides a reference to an action file (= a simple JSON file) then
    - all actions are recorded in that file unless it has already been recorded
    - at the end, once the minutes are generated, the action file is also updated with the (possibly) new content
    - there is also a simple extra JS file (in `ActionView`) to display the content in an HTML file. To test it properly, it has to be combined with, e.g., jekyll and our WG sites; that has been done on my local machine already, but needs real-life testing loading the files via real URL-s and not via localhost... (hence the need to merge it)
- If no config file is provided, nothing happens, actions are treated like they are so far.

### CODE REVIEW

**Comment by BigBlueHat** [comment]
Would you be upset if I made this use JSON-LD and an "append only" sort of storage (still in a local static file or files)?

Reasoning:
 - each of the actions have URLs already
 - append-only would mean allow us track when things are completed (it's a separate set of "statements") vs. updating the "status" in place
 - graphs are cool 😎 
 - linked data is what we're building after all 😉 

Thoughts?

**Comment by iherman** [comment]
- re JSON-LD: I am not sure what we would gain. When would I share this data with other datasets? Because if not, then what is the point?

    That being said, I guess it is only cosmetics, because the processing would not change...
- "append only": I am not sure what you mean. The present script is already 'append only', in the sense that items are only added by scribejs, and any removal must be done by separate actions directly (for now). Can you tell me more?

**Comment by iherman** [comment]
@BigBlueHat here is my question: what would be a reasonable service through browserview (I would like to avoid the github commit approach for all the reasons we already discussed). The only approach I can see now is:

- Adding a new field for accessing a (possible) action file via a URL. This would be a copy of what we do for nicknames
- If the conversion yields a new action content then, when the user clicks on the 'save' button (or via a separate button?) the new action file would be stored locally, alongside the downloaded minutes.

Ie, the user would still have to add the action file to the local repo and commit it (just like for minutes).

I do not really see any other option at the moment

(I full integration with github is a separate thing that may change that, but that is more complex...)

WDYT?

**Comment by iherman** [comment]
@BigBlueHat, not to be merged!

After some discussions with @gkellogg I am pursuing a different alternative: turn each action into an issue on, say, the json-ld-wg repository. It does require the github credentials, but that may be a better approach altogether. Until I have that as an alternative, this branch should be frozen... 

But it will take time. Octokat is o.k. but hopelessly underdocumented, so it is a struggle to find out how to to what must be done. But it should be solvable:-)

**Comment by BigBlueHat** [comment]
It does make sense to keep action items / issues in a single place. FWIW, I have some experience using https://github.com/octokit/rest.js (having used it for org/teams management at work). If you get the basics stubbed in, I'd be happy to help finish it off!

**Comment by BigBlueHat** [comment]
@iherman given your "not to be merged!" status on this one, I'm going to close it (which removes the merge pull request option), and we can reopen if/when needed. Hope that's OK! 😄

**Comment by iherman** [comment]
@bigbluehat, I have, by now, octocat under control :-), I just have to put everything together...

**Pull request closed without merging**
