### PR TITLE
Lint “lib/” and “test/” too; fix errors there; check linting on Travis

### PR DESCRIPTION
**Pull request by tripu**
To examine *actual* changes here post-#50, [review this diff instead](https://github.com/WileyLabs/scribejs/compare/eslint...w3c:tripu/eslint-in-travis?w=1).

TODO: lint `CGI/` too and fix errors there!

:warning: To be merged ***after* #50 is merged**.

### CODE REVIEW

**Comment by iherman** [comment]
@tripu I presume the travis problems are related to the fact that this should come after the other PR, right?

**Comment by tripu** [comment]
> *&ldquo;I presume the travis problems are related to the fact that this should come after the other PR, right?&rdquo;*

@iherman, it was some weird error on the part of Travis. I just restarted that one job that had failed, and it succeeded this time.

**Comment by iherman** [comment]
@tripu, o.k. 

Having looked at the proposed changes, they are fine with me, although I was not sure of the logic or rearranging some functions in one of the files...

**Comment by tripu** [comment]
> *&ldquo;I was not sure of the logic or rearranging some functions in one of the files...&rdquo;*

@iherman, I think it was [the rule `no-use-before-define`](https://eslint.org/docs/rules/no-use-before-define) the one that was triggering; some functions were invoked before they were defined in the file. I moved those function definitions. (It's not an error in JS, but with the arrival of new block-level keywords `let` and `const` it's better to have definitions before usage always, to avoid errors.)

**Pull request merged**
